version: "3.8"

services:
  frontend:
    build:
      context: ./FE_doc_ai
      dockerfile: Dockerfile
    container_name: frontend_service
    restart: always
    ports:
      - "5173:5173"  # Ensure this matches your Vite config
    depends_on:
      - backend
    env_file:
      - ./FE_doc_ai/.env

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: backend_service
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    command: ["sh", "-c", "./backend_start.sh"] # Delay to ensure DB is ready

  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-docai}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-doc_ai}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:

