version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: ./docker-config/local/FE/Dockerfile
    restart: always
    ports:
      - "5173:5173"  
    depends_on:
      - backend
    volumes:
      - ./FE_doc_ai/src:/app/src:delegated 
      - ./docker-config/local/FE/frontend_start.sh:/app/frontend_start.sh
      - /app/node_modules
    env_file:
      - ./FE_doc_ai/.env

  backend:
    build:
      dockerfile: ./docker-config/local/BE/Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./src:/app/src:delegated
    env_file:
      - .env

  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-docai}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-doc_ai}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
